spring:
  application:
    name: config-server-microservice
  cloud:
    config:
      server:
        git:
          uri: https://github.com/valentivuk/temperature-microservice-config
server:
  port: 8888
