version: "3.7"
services:
  config-server-microservice:
    image: config-server-microservice
    ports:
      - "8888:8888"
  eureka-server:
    image: eureka-server
    ports:
      - "8761:8761"
volumes:
  db-data:
