spring:
  application:
    name: humidity-microservice
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME:localhost}:${DB_PORT:54032}/${DB_NAME:humidity-database}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: create
  config:
    import: "optional:configserver:"
server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOSTNAME:eureka-server}:8761/eureka/
    instance:
      preferIpAddress: true
